# Generated by Django 4.2.2 on 2023-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='banner_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='list_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='screenshot_1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='screenshot_2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='screenshot_3',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
