# Generated by Django 4.2.2 on 2023-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShopApp', '0002_alter_videogame_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('playstation', 'Playstation'), ('xbox', 'XBOX')], default='PC', max_length=20),
        ),
    ]
