# Generated by Django 4.2.2 on 2023-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShopApp', '0003_alter_videogame_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(choices=[('pc', 'PC'), ('playstation', 'Playstation'), ('xbox', 'XBOX')], default='PC', max_length=20),
        ),
    ]
