# Generated by Django 4.2.2 on 2023-08-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShopApp', '0004_alter_videogame_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('racing', 'Racing'), ('horror', 'Horror')], default='PC', max_length=20),
        ),
    ]
