# Generated by Django 4.2.2 on 2023-08-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShopApp', '0008_order_orderitem_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
